# Generated by Django 4.0.5 on 2022-07-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Accepted',
        ),
    ]
